apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
      app: train-schedule-service
    spec:
      type: NodePort
      selector:
        app: train-schedule
      ports:
      - protocol: TCP
        port: 8080
        nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train-schedule
  name: train-schedule-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        run: train-schedule
    spec:
      containers:
      - image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        name: train-schedule
        ports:
        - containerPort: 8080
